server:
  port: 80
spring:
  application:
    name: service_zuul
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
zuul:
  strip-prefix: false
  routes:
    spring_security:
      path: /uaa/**
      serviceId: spring_security
    spring_order:
      path: /order/**
      serviceId: spring_order


