server:
  port: 80
spring:
  application:
    name: service_zuul
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  host:
    connect-timeout-millis: 150000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  strip-prefix: false
  routes:
    spring_security:
      path: /uaa/**
      serviceId: spring_security
    spring_order:
      path: /member/**
      serviceId: spring_member
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000



