server:
  port: 8090
spring:
  application:
    name: security
  main:
    allow-bean-definition-overriding: true #覆盖bean的注入
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://39.107.226.218:3306/cloud_zyou?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT
      username: root
      password: cpsoft
      # 初始连接数
      initial-size: 5
      # 最大连接池数量
      max-active: 100
      # 最小连接池数量
      min-idle: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心，相互注册使用IP地址
    #eureka客服端在收到最后一次心跳等待时间 单位秒。超过就剔除 （测试用）
    lease-expiration-duration-in-seconds: 2
    # eureka客服端向服务端发送心跳时间间隔 单位秒 （测试用）
    lease-renewal-interval-in-seconds: 1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka,http://localhost:9001/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
